const NUMERIC_PRECISION = 2;
const MAXIMUM_NUMERIC_PRECISION = 8;

const MAXIMUM_EXCHANGE_RATE_PRECISION = 6;

export {
  NUMERIC_PRECISION,
  MAXIMUM_NUMERIC_PRECISION,
  MAXIMUM_EXCHANGE_RATE_PRECISION,
};
